export const sample_foods = [
    {
        id: '1',
        name: 'Hamburger',
        cookTime: '5-10',
        price: 10,
        favorite: false,
        origins: ['America'],
        stars: 4,
        imageUrl: 'Burger.jpg',
        tags: ['FastFood', 'Hamburger', 'American'],
    },
    {
        id: '2',
        name: 'Cake',
        cookTime: '25-30',
        price: 32,
        favorite: true,
        origins: ['Europe', 'Asia'],
        stars: 4.5,
        imageUrl: 'Cake.jpg',
        tags: ['FastFood', 'Cake', 'Dessert'],
    },
    {
        id: '3',
        name: 'Fruit',
        cookTime: '3-5',
        price: 23,
        favorite: false,
        origins: ['Africa', 'Asia', 'Europe'],
        stars: 3.5,
        imageUrl: 'Fruit.jpg',
        tags: ['Dessert', 'Fruit'],
    },
    {
        id: '4',
        name: 'Korean Food',
        cookTime: '15-20',
        price: 32,
        favorite: false,
        origins: ['Korea'],
        stars: 4,
        imageUrl: 'KoreanFood.jpg',
        tags: ['Lunch', 'Korea', 'SlowFood'],
    },
    {
        id: '5',
        name: 'Pizza',
        cookTime: '15-20',
        price: 21,
        favorite: true,
        origins: ['Italy'],
        stars: 4.5,
        imageUrl: 'Pizza.jpg',
        tags: ['FastFood', 'Lunch', 'Italy', 'Pizza'],
    },
    {
        id: '6',
        name: 'Sea Food',
        cookTime: '20-25',
        price: 66,
        favorite: true,
        origins: ['Pacific Ocean'],
        stars: 5,
        imageUrl: 'SeaFood.jpg',
        tags: ['SlowFood', 'SeaFood', 'Ocean'],
    },
]

export const sample_tags = [
    { name: 'All', count: 6 },
    { name: 'FastFood', count: 3 },
    { name: 'SlowFood', count: 2 },
    { name: 'Lunch', count: 2 },
    { name: 'Hamburger', count: 1 },
    { name: 'Pizza', count: 1 },
    { name: 'Fruit', count: 1 },
    { name: 'Dessert', count: 1 },
]

export const sample_users = [
    {
        id: 1,
        name: "Huy",
        email: "22520553@gm.uit.edu.vn",
        password: '12345',
        address: 'HCM',
        isAdmin: true,
    },
    {
        id: 2,
        name: "Trong",
        email: "trong@gmail.com",
        password: 'abc123',
        address: 'HCM',
        isAdmin: false,
    },
]